### PR TITLE
Added custom button

### PR DESCRIPTION
**Pull request by deytulsi18**
added custom button with colour gradient

### CODE REVIEW

**Review by ksheetal — COMMENTED** [review]
Hi @deytulsi18 
Can you please attach the screenshot based upon your changes?

**Comment by deytulsi18** [comment]
Sure

**Comment by deytulsi18** [comment]
I cannot add add images here , no options are available.
can I send image in LinkedIn message

**Comment by deytulsi18** [comment]
I have sent connect request please accept I can send there.

**Comment by ksheetal** [comment]
> I cannot add add images here , no options are available.
> can I send image in LinkedIn message

Hi, Please see the format of this pull request.
https://github.com/Skill-Class/Tap-The-Unique/pull/17

**Review by ksheetal — CHANGES_REQUESTED** [review]
Hi @deytulsi18. 
The very first icon was good. if you can change the background colour of that as the background colour of the game that would be great. Also, we don't want any fancy changes in button. Please remove that gradient thing. 
Thanks.

**Comment by deytulsi18** [comment]
The PR I have made only have button updates not the icon

Please merge the PR, this one only includes button colour changes.

**Comment by deytulsi18** [comment]
Ok ,I'll change the icon background colour as it is in the game.

**Comment by deytulsi18** [comment]
Please assisgn the task to me

**Pull request closed without merging**
