### PR TITLE
Added button animations

### PR DESCRIPTION
**Pull request by beccadaniel**
animation

This pull request contains implementation for a simple animation on the Info Activity page. 
It also does some file formatting for the MainActivity.java file. I also had to fix some minor crash that's currently occurring on the master branch

### CODE REVIEW

**Comment by RonakAggarwal** [comment]
@beccadaniel Thanks for the efforts. I think animations between the buttons during play time doesn't look good because every animation requires a span of time and we have time constraints here because of the timer. So, Let's keep it simple during play time. It would be great if you could put some animations on the intro screen instead as there is no timer, animation would look more better.

As an example, In the intro screen, the game description can slide from upward and "play game" button slide from downward.
This is just an example, you can choose another animation as per your choice. 

For any doubts, we are open to discuss it here.

**Comment by beccadaniel** [comment]
Yeah @RonakAggarwal  I was concerned about that too. I'll make changes to this effect, thanks

**Review by ksheetal — APPROVED** [review]
Brilliant Work. :)

**Comment by ksheetal** [comment]
Dear @beccadaniel 
You’ve really proved your mettle as being the most reliable team player. I look forward to working on more projects with you!
All the best.

**Comment by RonakAggarwal** [comment]
Hey! @beccadaniel 
Your efforts are incredible, This project has taken a new shape by your efforts. Looking forward to do some more projects with you.
Thanks and All the best!

**Comment by beccadaniel** [comment]
Thank you @RonakAggarwal  @ksheetal  I look forward to doing more with you as well

**Pull request merged**
